.TH "md__projects_hermes_README" 3 "Sat Dec 23 2023" "Hermes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__projects_hermes_README \- Hermes - Messenger of the Gods 
 
.SH "<img src='https://github\&.com/cybercritter/hermes/actions/workflows/cmake-multi-platform\&.yml/badge\&.svg' alt='Multi Build Status'/>"
.PP
.SH "Welcome to my little notebook project\&."
.PP
This notebook project, called hermes, will allow for people to record their journey\&. 
.br
 Everyone's journey is different but have similar experiences\&. This application will help in documenting 
.br
 each journey by being able to pull from others experiences; thus not feel alone\&. 
.br
.PP
The hope is by connecting people with the same experiences; we can bridge the gap and reduce the 
.br
 appalling suicide rate amongst the non-binary and trans communities\&. Especially with young people\&.
.br
.SH "For the Nerds, like me, out there"
.PP
.SS "Here are some of the more specific details"
This project will use the following technologies\&. 1) \fCmariadb\fP --- SQL backend for data warehousing\&.
.IP "\(bu" 2
Before you go crazy and scream a nosql database will work much better; can you say mongodb with a 
.br
 straight face? While a nosql database is certainly interesting, I have a fondness for sql databases\&.
.br
 I am open to constructive discussion\&.\fBLet me emphasize, I will not get into a religious discussion on this matter! \fP 2) \fCwxWidgets\fP front end --- I do not have \fI\fBany\fP\fP experience with UI/UX design\&. I am an engineer by trade 
.br
 and my GUI's certainly reflect this deficiency\&. If you want to help, Please email me at \fCcybercritter@mac\&.com\fP 3) \fCJetBrains CLion\fP --- I use CLion as my IDE for all my C++ projects\&. I have included the project files as part of this repo\&.
.PP
.PP
As I use more 3rd party stuff, this list will be updated\&.
.PP
Thank you for going with me on this journey\&. 
.br
.PP
(C) Cybercritter 2023
